[project]
name = "degscore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  #"arnie>=0.2.7",
  "numpy>=2.3.4",
  "polars>=1.35.1",
  "viennarna>=2.7.0",
]
